import type { Patient, StructuredClinicalData, ClinicalSummaryData, ConversationMessage, MedicalDocument, TimelineEvent } from '@/types';

export const DEMO_PATIENT: Patient = {
  id: 'demo-patient',
  full_name: 'Rahul Kumar',
  date_of_birth: '1981-03-15',
  age: 45,
  gender: 'male',
  phone_number: '9876543210',
  preferred_language: 'en',
  abha_id: '12-3456-7890-1234',
  address: '123 MG Road, Bengaluru, Karnataka 560001',
  emergency_contact_name: 'Sunita Kumar',
  emergency_contact_phone: '9876543211',
  blood_group: 'B+',
  assigned_doctor_id: null,
  priority: 'normal',
  status: 'completed',
  history_mode: 'allopathic',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_CONVERSATION: ConversationMessage[] = [
  { role: 'assistant', content: 'I understand you have fever for 3 days. Can you tell me when this started?', section: 'chief_complaint' },
  { role: 'user', content: 'I have fever for 3 days. It started suddenly.', section: 'chief_complaint' },
  { role: 'assistant', content: 'How high is the fever? Have you measured it?', section: 'history_of_present_illness' },
  { role: 'user', content: 'It was 102 degrees yesterday. Comes down with medicine but returns.', section: 'history_of_present_illness' },
  { role: 'assistant', content: 'Do you have any other symptoms like cough, cold, body pain, or headache?', section: 'history_of_present_illness' },
  { role: 'user', content: 'Yes, I have body pain and mild headache. Also feeling weak.', section: 'history_of_present_illness' },
  { role: 'assistant', content: 'Do you have any previous medical conditions like diabetes, hypertension, or thyroid?', section: 'past_medical_history' },
  { role: 'user', content: 'I have diabetes for 5 years. Taking metformin.', section: 'past_medical_history' },
  { role: 'assistant', content: 'Have you had any surgeries in the past?', section: 'past_surgical_history' },
  { role: 'user', content: 'No surgeries.', section: 'past_surgical_history' },
  { role: 'assistant', content: 'What medications are you currently taking?', section: 'drug_history' },
  { role: 'user', content: 'Metformin 500 mg twice daily. Also took paracetamol for fever.', section: 'drug_history' },
  { role: 'assistant', content: 'Do you have any allergies to medications or food?', section: 'allergy_history' },
  { role: 'user', content: 'No known allergies.', section: 'allergy_history' },
  { role: 'assistant', content: 'Does anyone in your family have diabetes, hypertension, or heart disease?', section: 'family_history' },
  { role: 'user', content: 'My father has diabetes and mother has hypertension.', section: 'family_history' },
  { role: 'assistant', content: 'Do you smoke, consume alcohol, or have any specific dietary habits?', section: 'personal_history' },
  { role: 'user', content: 'I do not smoke. Occasional alcohol. Mostly vegetarian diet.', section: 'personal_history' },
];

export const DEMO_STRUCTURED_DATA: StructuredClinicalData = {
  chief_complaint: 'Fever for 3 days',
  history_of_present_illness: 'Sudden onset fever 3 days ago, measured up to 102°F. Responds to paracetamol but recurs. Associated with body pain, mild headache, and weakness. No cough or cold reported.',
  past_medical_history: 'Type 2 Diabetes Mellitus for 5 years, on Metformin.',
  past_surgical_history: 'No surgical history.',
  drug_history: 'Metformin 500 mg twice daily. Paracetamol as needed for fever.',
  allergy_history: 'No known allergies.',
  family_history: 'Father: Diabetes. Mother: Hypertension.',
  personal_history: 'Non-smoker. Occasional alcohol. Vegetarian diet.',
  review_of_systems: 'Fever, body pain, mild headache, weakness. No respiratory, cardiovascular, or gastrointestinal symptoms reported.',
  red_flags: [],
  missing_information: ['Vaccination history', 'Recent travel history', 'COVID-19 status'],
};

export const DEMO_SUMMARY: ClinicalSummaryData = {
  chief_complaint: 'Fever for 3 days',
  history_of_present_illness: 'Sudden onset fever 3 days ago, measured up to 102°F. Responds to paracetamol but recurs. Associated with body pain, mild headache, and weakness.',
  past_medical_history: 'Type 2 Diabetes Mellitus for 5 years, on Metformin.',
  past_surgical_history: 'No surgical history.',
  drug_history: 'Metformin 500 mg twice daily. Paracetamol as needed for fever.',
  allergy_history: 'No known allergies.',
  family_history: 'Father: Diabetes. Mother: Hypertension.',
  personal_history: 'Non-smoker. Occasional alcohol. Vegetarian diet.',
  review_of_systems: 'Fever, body pain, mild headache, weakness. No respiratory, cardiovascular, or GI symptoms.',
  previous_investigations: 'HbA1c: 8.2% (dated 15/08/2026) — above reference range. Fasting glucose: 142 mg/dL.',
  current_medications: 'Metformin 500 mg twice daily. Paracetamol 500 mg as needed for fever.',
  important_document_findings: 'HbA1c 8.2% indicates suboptimal glycemic control. Fasting glucose 142 mg/dL is elevated.',
  red_flags: [],
  missing_information: ['Vaccination history', 'Recent travel history', 'COVID-19 status'],
};

export const DEMO_DOCUMENTS: MedicalDocument[] = [
  {
    id: 'demo-doc-1',
    patient_id: 'demo-patient',
    file_name: 'blood_report_aug2026.pdf',
    file_type: 'application/pdf',
    file_size: 245000,
    storage_path: 'demo/blood_report.pdf',
    document_type: 'blood_report',
    processing_status: 'processed',
    uploaded_at: '2026-08-15T10:30:00Z',
    processed_at: '2026-08-15T10:31:00Z',
  },
  {
    id: 'demo-doc-2',
    patient_id: 'demo-patient',
    file_name: 'prescription_metformin.pdf',
    file_type: 'application/pdf',
    file_size: 180000,
    storage_path: 'demo/prescription.pdf',
    document_type: 'prescription',
    processing_status: 'processed',
    uploaded_at: '2026-08-10T14:00:00Z',
    processed_at: '2026-08-10T14:01:00Z',
  },
];

export const DEMO_TIMELINE: TimelineEvent[] = [
  {
    id: 'demo-tl-1',
    patient_id: 'demo-patient',
    event_date: '2021-05-10',
    event_type: 'diagnosis',
    event_title: 'Type 2 Diabetes Mellitus diagnosed',
    event_description: 'Diagnosed at Apollo Hospital. HbA1c was 9.1%.',
    source: 'patient',
    source_document_id: null,
    source_history_id: null,
    metadata: {},
    created_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'demo-tl-2',
    patient_id: 'demo-patient',
    event_date: '2021-05-10',
    event_type: 'prescription',
    event_title: 'Started Metformin 500 mg',
    event_description: 'Prescribed Metformin 500 mg twice daily after diabetes diagnosis.',
    source: 'document',
    source_document_id: 'demo-doc-2',
    source_history_id: null,
    metadata: {},
    created_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'demo-tl-3',
    patient_id: 'demo-patient',
    event_date: '2026-08-15',
    event_type: 'investigation',
    event_title: 'Blood investigation — HbA1c & Fasting Glucose',
    event_description: 'HbA1c: 8.2%, Fasting glucose: 142 mg/dL. HbA1c above target range.',
    source: 'document',
    source_document_id: 'demo-doc-1',
    source_history_id: null,
    metadata: { abnormal: true },
    created_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'demo-tl-4',
    patient_id: 'demo-patient',
    event_date: '2026-08-22',
    event_type: 'consultation',
    event_title: 'Fever for 3 days — current visit',
    event_description: 'Patient presents with fever, body pain, and weakness. Completing clinical history via MediKiosk.',
    source: 'patient',
    source_document_id: null,
    source_history_id: null,
    metadata: {},
    created_at: '2026-08-25T10:00:00Z',
  },
];

export const DEMO_EXTRACTED_MEDICATIONS = [
  { name: 'Metformin', dosage: '500 mg', frequency: 'Twice daily', duration: 'Ongoing' },
  { name: 'Paracetamol', dosage: '500 mg', frequency: 'As needed', duration: 'For fever' },
];

export const DEMO_EXTRACTED_INVESTIGATIONS = [
  { test_name: 'HbA1c', value: '8.2', unit: '%', reference_range: '< 7.0%', is_abnormal: true, date: '15/08/2026' },
  { test_name: 'Fasting Glucose', value: '142', unit: 'mg/dL', reference_range: '70-100 mg/dL', is_abnormal: true, date: '15/08/2026' },
  { test_name: 'Total Cholesterol', value: '180', unit: 'mg/dL', reference_range: '< 200 mg/dL', is_abnormal: false, date: '15/08/2026' },
];
